### ISSUE TITLE
Use icon library instead of the user copying the assets?

### ISSUE THREAD

**Issue by theoparis** [imagemarker/kveditor#1]
Nice library! I have encountered two issues with this:

1. As mentioned in the readme I currently have to copy assets to the public folder, however this does not work if I want them in /assets instead of / for example. A good solution would be to use something like react-feather (feather icons for react). 
2. For some reason I can't enter anything into the text fields for both key and values.

**Comment by theoparis** [comment]
Also, I got this error in the console:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

EDIT: this error and the problem 2 i had were both because of the onchange setting state. I used similar code from the example but I just needed `items={this.state.keyValues}` and not an onchange handler.

**Comment by erhangundogan** [comment]
@creepinson thanks for the issues and feedback. I will look into react-feather and possible solutions to manage assets.

Regarding to your second question, that might happen if you fall into state update loop. It's kinda race condition. 
There is one thing important to mention here `items` prop is **only needed for the first time init and It should not be reassigned.** The reason is component has it's own internal state to keep items. It doesn't rely on `items` prop when you start editing items. You can get update with `onChange` method as a notification but then you should not assign it back to the component.

**Comment by erhangundogan** [comment]
I am sorry closed mistakenly.

**Comment by erhangundogan** [comment]
There is no further commit on this issue so closing.
